apps/asset/urls.py
from django.urls import path, include

from .views import *

app_name = 'asset'

urlpatterns = [
    path('asset/', include([
        path('asset-list/', AssetListView.as_view(), name='asset_list'),
        path('asset-add/', AssetCreateView.as_view(), name='asset_add'),
        path('asset-update/<int:pk>/', AssetUpdateView.as_view(), name='asset_update'),
        path('asset-remove/<int:pk>/', AssetDeleteView.as_view(), name='asset_remove'),
        path('asset-add-category/', AssetCategoryCreateView.as_view(), name='asset_add_category'),
        path('asset-category-list/', AssetCategoryListView.as_view(), name='asset_category_list'),
        path('asset-category-update/<int:pk>/', AssetCategoryUpdateView.as_view(), name='asset_category_update'),
        path('asset-damage/', AssetAssignListView.as_view(), name='asset_assign'),
        path('asset-assign-create/<int:pk>/', AssetAssign.as_view(), name='asset_assign_create'),
        path('asset-unassign/', ajax_asset_unassign, name='asset_unassign'),
        path('asset-assign-ownership/', ajax_asset_assign, name='asset_assign_ownership'),
        path('asset-damaged-assets/', ajax_asset_defected, name='asset_damaged_assets'),

        # below is the url for the user perspective assetview
        path('user-asset-list/', UserAssetListView.as_view(), name='user_asset_list'),

    ]))
]

apps/drar/urls.py
from datetime import datetime

from django.urls import path, register_converter, include

from apps.drar.views import *


class DateConverter:
    regex = r'\d{2}-\d{2}-\d{4}'

    def to_python(self, value):
        try:
            return datetime.strptime(value, '%d-%m-%Y').date()
        except Exception as e:
            raise Http404("This Date is not Valid.")

    def to_url(self, value):
        return value


register_converter(DateConverter, 'date_pattern')

app_name = 'drar'

urlpatterns = [
    path('drar/', include([
        path('', DrarManageView.as_view(), name="drar-today"),
        path('<date_pattern:date>/', DrarManageView.as_view(), name="drar-create"),
        path('<date_pattern:date>/note-<int:pk>/', DrarManageView.as_view(), name="drar-update"),
        path('<date_pattern:date>/note-<int:pk>/completed/', DrarCompleteView.as_view(), name="drar-complete-task"),
        path('<date_pattern:date>/note-<int:pk>/delete/', DrarDeleteView.as_view(), name="drar-delete"),
        path('<date_pattern:date>/note-<int:pk>/copy/', CopyDrarTask.as_view(), name="copy-drar-task"),
        path('configuration/', DrarConfigurationView.as_view(), name="drar-configuration"),
        path('shared/', UsersSharedDrarListView.as_view(), name="shared-drar-users"),
        path('shared/emp-<int:user_pk>/', SharedDrarListView.as_view(), name="shared-drar-list"),
        path('shared/emp-<int:user_pk>/<date_pattern:date>/', SharedDrarListView.as_view(), name="shared-drar-dated-list"),
    ])),
]

apps/leave/urls.py
from django.urls import path, include

from apps.leave.views import *

app_name = 'leave'


urlpatterns = [
    path('leaves/', include([
        path('', LeaveRequestListView.as_view(), name="list"),
        path('<int:pk>/view/', LeaveRequestDetailView.as_view(), name="view"),
        path('holidays/', HolidayListView.as_view(), name="holiday-list"),
        path('monthly-user-leaves/', UserLeaveView.as_view(), name="user-leave"),
        path('annual-user-leaves/', UserAnnualLeaveView.as_view(), name="annual-user-leave"),
        path('new-requests/', NewLeaveRequestsListView.as_view(), name="new-leave-requests"),
        path('new-requests/<int:pk>/modify/', NewLeaveRequestsDetailView.as_view(), name="detail"),

    ])),
    path('wfh/', include([
        path('', WFHRequestListView.as_view(), name="wfh-list"),

        path('requests/', WFHListView.as_view(), name="wfh-hr-list"),
        path('requests/<int:pk>/approve/', WFHUpdateView.as_view(), name="wfh-hr-update"),
    ])),
    path('late-attendance/', include([
        path('', LateAttendanceListView.as_view(), name="late-attendance-list"),
    ])),
]

apps/user/urls.py
from django.conf import settings
from django.urls import path, include, reverse


from apps.user.api import UserAPIView, QRCodeView, scanned_login
from apps.user.views import UserProfileUpdateView

app_name = "user"


api_urlpatterns = [
    path('user-profile/', UserAPIView.as_view(), name="user-profile"),
    path('qr_code/', QRCodeView.as_view(), name="qrcode"),
    path('login-with-scan/', scanned_login, name="scanned_login"),

]


urlpatterns = [
    path('api/v1/', include(api_urlpatterns)),
    path('user-profile-update/<int:pk>/', UserProfileUpdateView.as_view(), name='user_profile_update'),
]

fims/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin, messages
from django.shortcuts import redirect
from django.urls import path, include, reverse
import debug_toolbar
from django.conf.urls import url

from rest_auth.views import (
    LogoutView, UserDetailsView, PasswordChangeView,
    PasswordResetView, PasswordResetConfirmView
)
from apps.generic.login import LoginView as APILoginView

from apps.generic.index import HomeView, trigger_error, LoginView as WebLoginView
from apps.root import root


def redirect_to_login(request):
    """
    this view is used to disable allauth signup which redirects on failed social login;
    redirect it to settings.LOGIN_URL
    """
    messages.warning(request, "No account found with the registered email address.")
    return redirect(reverse(settings.LOGIN_URL))


urlpatterns = [
    path('fegnomin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    # path('login/', LoginView.as_view(), name='login'),
    path('login/', WebLoginView.as_view(template_name="paper/login.html"), name='login'),
    path('', HomeView.as_view(), name="dashboard-index"),
    # path('', login_required(RedirectView.as_view(pattern_name='leave:list')), name="dashboard-index"),
    path('', include("apps.accounts.urls")),
    path('', include("apps.asset.urls")),
    path('', include("apps.documents.urls")),
    path('', include("apps.leave.urls")),
    path('', include("apps.petty.urls")),
    path('', include("apps.project.urls")),
    path('', include("apps.user.urls")),
    path('', include("apps.payslip.urls")),
    path('sop/', include("apps.sop.urls")),
    path('', include("apps.drar.urls")),
    path('api/v1/bcard/', include("apps.bcard")),
    path('careers/recruitment/', include("apps.recruitment.urls")),
    path('api/v1/', root, name="root"),
    path('api/v1/', include('apps.leave.api_urls')),

    # path(r'nda-agreed-contents/', include('private_files.urls')),
    path('sentry-debug/', trigger_error),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/social/signup/', redirect_to_login, name="socialaccount_signup"),
    path('accounts/', include('allauth.urls')),

    path('rest-auth/', include([
        # URLs that do not require a session or valid token
        url(r'^password/reset/$', PasswordResetView.as_view(),
            name='rest_password_reset'),
        url(r'^password/reset/confirm/$', PasswordResetConfirmView.as_view(),
            name='rest_password_reset_confirm'),
        url(r'^login/$', APILoginView.as_view(), name='rest_login'),
        # URLs that require a user to be logged in with a valid session / token.
        url(r'^logout/$', LogoutView.as_view(), name='rest_logout'),
        url(r'^user/$', UserDetailsView.as_view(), name='rest_user_details'),
        url(r'^password/change/$', PasswordChangeView.as_view(),
            name='rest_password_change'),
    ])),
    # path('base.html', TemplateView.as_view(template_name="paper/layout.html")),
    # path('dashboard.html', TemplateView.as_view(template_name="paper/examples/dashboard.html")),
    # path('icons.html', TemplateView.as_view(template_name="paper/examples/icons.html")),
    # path('notifications.html', TemplateView.as_view(template_name="paper/examples/notifications.html")),
    # path('tables.html', TemplateView.as_view(template_name="paper/examples/tables.html")),
    # path('typography.html', TemplateView.as_view(template_name="paper/examples/typography.html")),
    # path('user.html', TemplateView.as_view(template_name="paper/examples/user.html")),
    path('baton/', include('baton.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]


if settings.DEBUG:
    urlpatterns.extend([
        *static(settings.STATIC_URL, document_root=os.path.join(settings.BASE_DIR, settings.STATICFILES_DIRS[0])),
        *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    ])

apps/utils/forms.py
from django import forms
from django.conf import settings
from django.forms import DateField, DateTimeField, TimeField, Textarea, ModelForm
from django.forms.utils import ErrorList


class BootstrapFormMixin(object):
    """
    Sample Django Form To add Bootstrap's Form Control class to every field.
    """
    def __init__(self, request=None, *args, **kwargs):
        if request:
            self.request = request
        super(BootstrapFormMixin, self).__init__(*args,  **kwargs)
        for field in getattr(self, 'fields', []):
            field_attr = self.fields[field].widget.attrs
            field_attr.update({
                'class': field_attr.get('class', '') + ' form-control form-control-alternative ',
                'placeholder': self.fields[field].label or field
            })
            if type(self.fields[field]) == DateField:
                field_attr['class'] += ' datepicker'
                field_attr['data-date-format'] = "dd-mm-yyyy"
                field_attr['autocomplete'] = "off"
                self.fields[field].widget.foramt = settings.DATE_INPUT_FORMATS[0]
                self.fields[field].input_formats = settings.DATE_INPUT_FORMATS

            elif type(self.fields[field]) == TimeField:
                field_attr['class'] += ' timepicker'
                field_attr['autocomplete'] = "off"

            elif type(self.fields[field]) == DateTimeField:
                field_attr['class'] += ' datetimepicker'
                field_attr['data-date-format'] = "dd-mm-yyyy"
                field_attr['autocomplete'] = "off"
                self.fields[field].widget.foramt = settings.DATE_INPUT_FORMATS[0]
                self.fields[field].input_formats = settings.DATE_INPUT_FORMATS

            elif type(self.fields[field]) == Textarea:
                field_attr['rows'] = '2'


class BootstrapModelForm(BootstrapFormMixin, ModelForm):
    pass

templates/paper/utils/_user_permission_menus.html
{% load py_utils static %}
{% if request.user.is_devops %}
<li class="treeview">

    <a data-toggle="collapse" href="#componentsExamples1" class="collapsed" aria-expanded="false">
        <i class="nc-icon nc-layout-11"></i>
        <p>Devops<b class="caret"></b>        </p>
    </a>
    <div class="collapse" id="componentsExamples1" style="">
        <ul class="nav" style="">
            <li>
                <a href="{% url 'project:hosting-list' %}">
<!--                    <i class="fa fa-clone"></i>-->
                    Hosting List
                </a>
            </li>
        </ul>
    </div>
</li>
{% endif %}

{% if request.user.is_in_business %}
<li class="treeview">

    <a data-toggle="collapse" href="#componentsExamples2" class="collapsed" aria-expanded="false">
        <i class="nc-icon nc-layout-11"></i>
        <p>Business<b class="caret"></b>        </p>
    </a>
    <div class="collapse" id="componentsExamples2" style="">
        <ul class="nav" style="">

            <li>
                <a href="{% url 'project:project-list' %}">
<!--                <i class="fa fa-hdd-o"></i>-->
                    Projects & Clients
                </a>
            </li>
            <li>
                <a href="{% url 'project:create_prospect' %}">Prospects </a>
            </li>
             <li >
                 <a href="{% url 'accounts:proforma-list' %}">
<!--                 <i class="fa fa-th-list" aria-hidden="true"></i> -->
                     <span> Proforma </span>
                </a>
            </li>
             <li >
                 <a href="{% url 'project:inflow_list' %}">
<!--                 <i class="fa fa-th-list" aria-hidden="true"></i> -->
                     <span> Inflow Outflow </span>
                </a>
            </li>

        </ul>
    </div>
</li>
{% endif %}

{% if request.user.is_hr %}
{% no_of_pending_leaves as pending_leaves %}
<li class="treeview" >
    <a data-toggle="collapse" href="#componentsExamples3" class="collapsed" aria-expanded="false">
        <i class="nc-icon nc-layout-11"></i>
                <p>Human Resource<b class="caret"></b></p>
    </a>
    <div class="collapse" id="componentsExamples3" style="">
        <ul class="nav" style="">

            <li>
                <a href="{% url 'leave:new-leave-requests' %}">
                    {% if pending_leaves%} <span class="label bg-yellow">{{ pending_leaves }}</span>   New Requests {% endif %}
                </a>
            </li>
            <li>
                <a href="{% url 'leave:wfh-hr-list' %}">
                    WFH Requests
                </a>
            </li>
            <li>
                <a href="{% url 'payslip:payslip-list' %}">
<!--                    <i class="fa fa-ellipsis-v"></i>-->
                    Payslip List
                </a>
            </li>
            <li>
                <a href="{% url 'leave:annual-user-leave' %}">
<!--                    <i class="fa fa-building"></i>-->
                    Annual Summary
                </a>
            </li>
            <li>
                <a href="{% url 'leave:user-leave' %}">
<!--                    <i class="fa fa-calendar-check-o"></i>-->
                    Month Summary
                </a>
            </li>
            <li>
                <a href="{% url 'leave:late-attendance-list' %}">
<!--                    <i class="fa fa-calendar-times-o"></i>-->
                    Late Attendance
                </a>
            </li>
            <li>

                <a href="{% url 'asset:asset_list' %}">
<!--                    <i class="fa fa-calendar-times-o"></i>  -->
                    Assets
                </a>
            </li>

        </ul>
    </div>
</li>

{% endif %}

templates/paper/utils/admin_menu.html
<li class="treeview" >

    <a data-toggle="collapse" href="#componentsExamples" class="collapsed" aria-expanded="false">
        <i class="nc-icon nc-layout-11"></i>
        <p>
            Administration<b class="caret"></b>
        </p>
    </a>
    <div class="collapse hide" id="componentsExamples" style="">
        <ul class="nav" style="">
            <li>
            <a href="{% url 'admin:index' %}" target="_blank">
                <i class="fa fa-dashboard"></i>  Admin Panel
            </a>
        </li>
        {% if request.user.is_manager %}
        <li >
            <a href="{% url 'petty:dashboard-petty' %}">
                <i class="fa fa-th-list" aria-hidden="true"></i> <span>Petty</span>
            </a>
        </li>
        {% endif %}

        </ul>
    </div>
</li>

templates/paper/utils/business_menu.html
    <li>
    <a href="javascript:;">
        <i class="nc-icon nc-diamond"></i>
        <p>business Item 1 </p>
    </a>
</li>
<li>
    <a href="javascript:;">
        <i class="nc-icon nc-diamond"></i>
        <p>business Item 2 </p>
    </a>
</li>
<li>
    <a href="javascript:;">
        <i class="nc-icon nc-diamond"></i>
        <p>business Item 3 </p>
    </a>
</li>

templates/paper/utils/common_menu.html
<ul class="nav">
<!--    {% if settings.DEBUG %}-->
<!--        {% include 'paper/utils/example_menu.html' %}-->
<!--    {% endif %}-->

{% block nav_links_ul %}
<ul class="sidebar-menu" >
    {% block nav_links_outer %}
    <li class="header">{% block nav_heading %}MAIN NAVIGATION{% endblock %}</li>

    {% block nav_links %}
    <li>
        <a href="{% url 'user:user_profile_update' request.user.id %}">
               <i class="nc-icon nc-single-02"></i> <span>User Profile</span>
        </a>
    </li>
    <li>
        <a href="{% url 'drar:drar-today' %}">
            <i class="fa fa-calendar-check-o"></i> <span>Personal DRAR</span>
        </a>
    </li>
    <li>
        <a href="{% url 'leave:holiday-list' %}">
            <i class="fa fa-calendar-check-o"></i> <span>Holidays</span>
        </a>
    </li>
    <li>
        <a href="{% url 'leave:list' %}">
            <i class="fa fa-sign-out" aria-hidden="true"></i><span>Leaves</span>
        </a>
    </li>
    <!-- li>
        <a href="{% url 'leave:wfh-list' %}">
            <i class="fa fa-sign-out" aria-hidden="true"></i> <span>Work form home <img src="https://www.svgrepo.com/show/100644/new.svg" width="30" alt=""> </span>
        </a>
    </li -->
    <li>
        <a href="{% url 'documents:circular-list' %}">
            <i class="fa fa-newspaper-o" aria-hidden="true"></i><span>Circulars</span>
        </a>
    </li>
    <li>
        <a href="{% url 'documents:publicdocuments-list' %}">
            <i class="fa fa-braille" aria-hidden="true"></i><span>Policy documents</span>
        </a>
    </li>
    {% if not request.user.is_manager %}
    <li>
        <a href="{% url 'payslip:payslip-my-list' %}">
            <i class="fa fa-book" aria-hidden="true"></i><span>PaySlips</span>
        </a>
    </li>
    {% endif %}
    <li>
        <a href="{% url 'documents:userdocuments-list' %}">
            <i class="fa fa-book" aria-hidden="true"></i><span>My Documents</span>
        </a>
    </li>
    <li>
        <a href="{% url 'asset:user_asset_list' %}">
            <i class="fa fa-book" aria-hidden="true"></i><span>Asset List</span>
        </a>
    </li>

    {% include 'paper/utils/_user_permission_menus.html' %}
    {% if user.is_superuser %}
    {% include 'paper/utils/admin_menu.html' %}
    {% endif %}
    {% endblock nav_links %}
    {% endblock nav_links_outer %}
</ul>
{% endblock nav_links_ul %}



</ul>

templates/paper/utils/devops_menu.html
<li>
    <a href="javascript:;">
        <i class="nc-icon nc-diamond"></i>
        <p>DevOps Item 1 </p>
    </a>
</li>
<li>
    <a href="javascript:;">
        <i class="nc-icon nc-diamond"></i>
        <p>DevOps Item 2 </p>
    </a>
</li>
<li>
    <a href="javascript:;">
        <i class="nc-icon nc-diamond"></i>
        <p>DevOps Item 3 </p>
    </a>
</li>

templates/paper/utils/example_menu.html
<li>
    <a data-toggle="collapse" href="#componentsExamples" class="" aria-expanded="true">
        <i class="nc-icon nc-layout-11"></i>
        <p>
            Examples <b class="caret"></b>
        </p>
    </a>
    <div class="collapse show" id="componentsExamples" style="">
        <ul class="nav">
            <li>
                <a href="/dashboard.html">
                    <span class="sidebar-mini-icon">GM</span>
                    <span class="sidebar-normal"> Dashboard </span>
                </a>
            </li>
            <li>
                <a href="/icons.html">
                    <span class="sidebar-mini-icon">GM</span>
                    <span class="sidebar-normal"> Icons </span>
                </a>
            </li>
            <li>
                <a href="/notifications.html">
                    <span class="sidebar-mini-icon">GM</span>
                    <span class="sidebar-normal"> Notifications </span>
                </a>
            </li>
            <li>
                <a href="/tables.html">
                    <span class="sidebar-mini-icon">GM</span>
                    <span class="sidebar-normal"> Tables </span>
                </a>
            </li>
            <li>
                <a href="/typography.html">
                    <span class="sidebar-mini-icon">GM</span>
                    <span class="sidebar-normal"> Typography </span>
                </a>
            </li>
            <li>
                <a href="/user.html">
                    <span class="sidebar-mini-icon">GM</span>
                    <span class="sidebar-normal"> User </span>
                </a>
            </li>
        </ul>
    </div>
</li>

templates/paper/utils/footer.html
{% block footer %}
<footer class="footer w-100 row" >
    <div class="container-fluid">
        <div class="row">
            <nav class="footer-nav">
                <ul>
                    {% block footer_links %}
                    <li><a href="https://www.fegno.com" target="_blank">www.fegno.com </a></li>
                    {% endblock %}
                </ul>
            </nav>
            <div class="credits ml-auto">
                  <span class="copyright">
                    {% block footer_message %}© 2021, made with <i class="fa fa-heart heart"></i> by Fegno Technologies {% endblock %}
                  </span>
            </div>
        </div>
    </div>
</footer>
{% endblock %}

templates/paper/utils/hr_menu.html
<li>
    <a href="javascript:;">
        <i class="nc-icon nc-diamond"></i>
        <p>HR Item 1 </p>
    </a>
</li>
<li>
    <a href="javascript:;">
        <i class="nc-icon nc-diamond"></i>
        <p>HR Item 2 </p>
    </a>
</li>
<li>
    <a href="javascript:;">
        <i class="nc-icon nc-diamond"></i>
        <p>HR Item 3 </p>
    </a>
</li>

templates/paper/utils/navbar_header.html
    <!-- Navbar -->{% load static i18n %}

    <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
      <div class="container-fluid">
        <div class="navbar-wrapper">
          <div class="navbar-toggle">
            <button type="button" class="navbar-toggler">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </button>
          </div>
        <a class="navbar-brand text-capitalize" href="#">
            <p style="max-width: 62vw;overflow: hidden;text-overflow: ellipsis;">Fegno Internal Management System</p>
            <div class="ripple-container"></div>
        </a>

          <a class="navbar-brand" href="javascript:;">{% block title %}{% endblock %}</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-bar navbar-kebab"></span>
          <span class="navbar-toggler-bar navbar-kebab"></span>
          <span class="navbar-toggler-bar navbar-kebab"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navigation">
          <form>
            <div class="input-group no-border">
              <input type="text" value="" class="form-control" placeholder="Search...">
              <div class="input-group-append">
                <div class="input-group-text">
                  <i class="nc-icon nc-zoom-split"></i>
                </div>
              </div>
            </div>
          </form>
          <ul class="navbar-nav">
            <li class="nav-item btn-rotate dropdown">
              <a class="nav-link dropdown-toggle" href="" id="example" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="nc-icon nc-bell-55"></i>
                <p>
                  <span class="d-lg-none d-md-block">Some Actions</span>
                </p>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink2">
                {% block notifications %}
                {% endblock %}

              </div>

            </li>
          </ul>

          {% if request.user.is_authenticated %}
                   <ul class="navbar-nav">
                      <li class="nav-item btn-rotate dropdown">
                          <a class="nav-link dropdown-toggle" href="http://example.com" id="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="nc-icon nc-single-02"></i>
                          </a>
                          {% block menu_footer %}
                          {% comment %}
                          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                                <a class="dropdown-item" href="{% url 'logout' %}">Sign Out</a>
<!--                                            <a href="{% url 'password_change' %}" class="btn btn-default ">-->
<!--                                              <i class="fa fa-braille" aria-hidden="true"></i><span>Change password</span>-->
<!--                                              </a>-->
<!--                                            <a href="{% url 'logout' %}" class="btn btn-default ">-->
<!--                                              <i class="fa fa-sign-out" aria-hidden="true">Sign out</i></a>-->

                          </div>
                          {% endcomment %}
                          {% endblock %}
                      </li>
                    </ul>
          {% endif %}
          </div>
        </div>
    </nav>
    <!-- End Navbar -->

templates/paper/utils/new_candidate_menu.html
<ul class="nav">
    <!--    {% if settings.DEBUG %}-->
    <!--        {% include 'paper/utils/example_menu.html' %}-->
    <!--    {% endif %}-->

    {% block nav_links_ul %}
    <ul class="sidebar-menu" >
        {% block nav_links_outer %}
        <li class="header">{% block nav_heading %}MAIN NAVIGATION{% endblock %}</li>

        {% block nav_links %}
        {% if request.user.new_candidate_form_is_in_draft_mode %}
        <li>
            <a href="{% url 'onboarding:general-information' %}">
                <i class="fa fa-user"></i> <span>General Information</span>
            </a>
        </li>
        <li>
            <a href="{% url 'onboarding:complete-profile' %}">
                <i class="fa fa-user"></i> <span>Complete Profile</span>
            </a>
        </li>
        <li>
            <a href="{% url 'onboarding:add-documents' %}">
                <i class="fa fa-file" aria-hidden="true"></i><span>Add Documents</span>
            </a>
        </li>
        <li>
            <a href="{% url 'onboarding:submit' %}">
                <i class="fa fa-cloud" aria-hidden="true"></i><span>Submit Your Profile</span>
            </a>
        </li>
        {% endif %}
        <li>
            <a href="{% url 'onboarding:information' %}">
                <i class="fa fa-sitemap" aria-hidden="true"></i><span>Information</span>
            </a>
        </li>
        {% endblock nav_links %}
        {% endblock nav_links_outer %}
    </ul>
    {% endblock nav_links_ul %}



</ul>

templates/paper/utils/user_menu.html
<div class="user">
    <div class="photo">
        <img src="{{ user.avatar_url | default:settings.DEFAULT_FEMALE_PROFILE_IMAGE }}">
    </div>
    <div class="info">

        <span data-toggle="collapse" href="#collapseExample" class="collapsed " aria-expanded="false">
            {{ user.get_full_name|default:"Anonymous" }}
            <b class="caret"></b>
        </span>
        <!--<div class="collapse" id="collapseExample" style="">
            <ul class="nav">
                <li>
                    <a href="#">
                        <span class="sidebar-mini-icon">MP</span>
                        <span class="sidebar-normal">My Profile</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="sidebar-mini-icon">EP</span>
                        <span class="sidebar-normal">Edit Profile</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="sidebar-mini-icon">S</span>
                        <span class="sidebar-normal">Settings</span>
                    </a>
                </li>

            </ul>
        </div>-->
    </div>
</div>