apps/asset/urls.py
from django.urls import path, include

from .views import *

app_name = 'asset'

urlpatterns = [
    path('asset/', include([
        path('asset-list/', AssetListView.as_view(), name='asset_list'),
        path('asset-add/', AssetCreateView.as_view(), name='asset_add'),
        path('asset-update/<int:pk>/', AssetUpdateView.as_view(), name='asset_update'),
        path('asset-remove/<int:pk>/', AssetDeleteView.as_view(), name='asset_remove'),
        path('asset-add-category/', AssetCategoryCreateView.as_view(), name='asset_add_category'),
        path('asset-category-list/', AssetCategoryListView.as_view(), name='asset_category_list'),
        path('asset-category-update/<int:pk>/', AssetCategoryUpdateView.as_view(), name='asset_category_update'),
        path('asset-damage/', AssetAssignListView.as_view(), name='asset_assign'),
        path('asset-assign-create/<int:pk>/', AssetAssign.as_view(), name='asset_assign_create'),
        path('asset-unassign/', ajax_asset_unassign, name='asset_unassign'),
        path('asset-assign-ownership/', ajax_asset_assign, name='asset_assign_ownership'),
        path('asset-damaged-assets/', ajax_asset_defected, name='asset_damaged_assets'),

        # below is the url for the user perspective assetview
        path('user-asset-list/', UserAssetListView.as_view(), name='user_asset_list'),

    ]))
]

fims/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin, messages
from django.shortcuts import redirect
from django.urls import path, include, reverse
import debug_toolbar
from django.conf.urls import url

from rest_auth.views import (
    LogoutView, UserDetailsView, PasswordChangeView,
    PasswordResetView, PasswordResetConfirmView
)
from apps.generic.login import LoginView as APILoginView

from apps.generic.index import HomeView, trigger_error, LoginView as WebLoginView
from apps.root import root


def redirect_to_login(request):
    """
    this view is used to disable allauth signup which redirects on failed social login;
    redirect it to settings.LOGIN_URL
    """
    messages.warning(request, "No account found with the registered email address.")
    return redirect(reverse(settings.LOGIN_URL))


urlpatterns = [
    path('fegnomin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    # path('login/', LoginView.as_view(), name='login'),
    path('login/', WebLoginView.as_view(template_name="paper/login.html"), name='login'),
    path('', HomeView.as_view(), name="dashboard-index"),
    # path('', login_required(RedirectView.as_view(pattern_name='leave:list')), name="dashboard-index"),
    path('', include("apps.accounts.urls")),
    path('', include("apps.asset.urls")),
    path('', include("apps.documents.urls")),
    path('', include("apps.leave.urls")),
    path('', include("apps.petty.urls")),
    path('', include("apps.project.urls")),
    path('', include("apps.user.urls")),
    path('', include("apps.payslip.urls")),
    path('sop/', include("apps.sop.urls")),
    path('', include("apps.drar.urls")),
    path('api/v1/bcard/', include("apps.bcard")),
    path('careers/recruitment/', include("apps.recruitment.urls")),
    path('api/v1/', root, name="root"),
    path('api/v1/', include('apps.leave.api_urls')),

    # path(r'nda-agreed-contents/', include('private_files.urls')),
    path('sentry-debug/', trigger_error),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/social/signup/', redirect_to_login, name="socialaccount_signup"),
    path('accounts/', include('allauth.urls')),

    path('rest-auth/', include([
        # URLs that do not require a session or valid token
        url(r'^password/reset/$', PasswordResetView.as_view(),
            name='rest_password_reset'),
        url(r'^password/reset/confirm/$', PasswordResetConfirmView.as_view(),
            name='rest_password_reset_confirm'),
        url(r'^login/$', APILoginView.as_view(), name='rest_login'),
        # URLs that require a user to be logged in with a valid session / token.
        url(r'^logout/$', LogoutView.as_view(), name='rest_logout'),
        url(r'^user/$', UserDetailsView.as_view(), name='rest_user_details'),
        url(r'^password/change/$', PasswordChangeView.as_view(),
            name='rest_password_change'),
    ])),
    # path('base.html', TemplateView.as_view(template_name="paper/layout.html")),
    # path('dashboard.html', TemplateView.as_view(template_name="paper/examples/dashboard.html")),
    # path('icons.html', TemplateView.as_view(template_name="paper/examples/icons.html")),
    # path('notifications.html', TemplateView.as_view(template_name="paper/examples/notifications.html")),
    # path('tables.html', TemplateView.as_view(template_name="paper/examples/tables.html")),
    # path('typography.html', TemplateView.as_view(template_name="paper/examples/typography.html")),
    # path('user.html', TemplateView.as_view(template_name="paper/examples/user.html")),
    path('baton/', include('baton.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]


if settings.DEBUG:
    urlpatterns.extend([
        *static(settings.STATIC_URL, document_root=os.path.join(settings.BASE_DIR, settings.STATICFILES_DIRS[0])),
        *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    ])

apps/asset/models.py
import datetime

from django.db import models


# Create your models here.
from django.conf import settings
from django.db import models


class AssetCategory(models.Model):
    """
    AssetCategory model consist of type or category of an asset
    """
    name = models.CharField(max_length=100)
    count = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name


class Component(models.Model):
    """
    Component model consists of details about the assets
    ----------------------------------------------------
    defected_by is used to indicate component has been defected by which user
    and is foreign key to User model..

    name: name of the component or asset
    code:code for each component it should contain a unique code
    _is_vacant :component is assigned or unassigned
    category: category of the component eg:system,pendrive,harddisk
    _is_defected :component is destroyed or not
    defected_by :specifies the user which damaged or defected the product

    """
    name = models.CharField(max_length=200, blank=True, null=True)
    code = models.CharField(max_length=10, blank=True, null=True,unique=True)
    price = models.FloatField(null=True, blank=True)

    _is_vacant = models.BooleanField(default=True)  # component is assigned or unassigned
    category = models.ForeignKey(AssetCategory, on_delete=models.CASCADE)
    _is_defected = models.BooleanField(default=False)  # component is destroyed or not
    defected_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Components'
        ordering = ['-id']

    @property
    def is_vacant(self):
        return self._is_vacant  # to get the value of private variable _is_vacant

    def assign_to(self, user, fromdate):
        self.unassign_component()
        # assign to some user
        self._is_vacant = False
        self.save()
        Ownership.objects.create(user=user, from_date=fromdate, component=self)

    def unassign_component(self, defected_by=None):
        """
        unassign_component is function to unassign assets or components,
        we can also specify whether the asset has been defected or not ,
        if defected, we can specify the user who destroyed it .
        """
        ownership = Ownership.get_ownership(component=self)
        if ownership:
            ownership.to_date = datetime.datetime.now(tz=datetime.timezone.utc)
            ownership.save()
        self.defected_by = defected_by
        self._is_vacant = True
        self.save()

    @property
    def is_defected(self):
        return self._is_defected

    def __str__(self):
        return f'{self.name} ({self.code})'

    def mark_damaged_assets(self, user):

        ownership = Ownership.objects.get(component=self)
        print("dsssssssssss", self, ownership)
        self._is_defected = True
        ownership.defected = True
        self.unassign_component(user)
        self.save()

    def assign_to(self, user):
        self.unassign()
        # assign to some user
        # set _is_vaccent = False
        pass

    def unassign(self, defected_by=None):
        ownership = Ownership.get_ownership(component=self)
        if ownership:
            ownership.to_date = datetime.now()
            # ownership.defected = defected_by and ownership.user == defected_by
            ownership.save()
        self.defected_by = defected_by
        self.save()


class Ownership(models.Model):
    """
    Ownership model contains details about ownership of the component or asset
    --------------------------------------------------------------------------
    from_date: Date from which asset is assigned
    to_date: Date upto which asset is unassigned
    user: foreignkey variable which user is assigned this asset
    component: foreignkey variable which asset is assigned

    """
    from_date = models.DateTimeField(default=datetime.datetime.now)
    to_date = models.DateTimeField(null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    component = models.ForeignKey(Component, on_delete=models.CASCADE)
    defected = models.BooleanField(default=False)
    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.user.username

    @classmethod
    def get_ownership(cls, component):

        """    get the ownership details of recently assigned owner   """
        return Ownership.objects.filter(component=component, to_date=None).order_by('-id').first()

apps/asset/views.py
import datetime

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count, Q
from django.shortcuts import redirect

# Create your views here.
from django.urls import reverse, reverse_lazy

from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.edit import DeleteView

from apps.asset.forms import AssignForm
from apps.asset.models import Ownership, Component, AssetCategory
from apps.user.models import User
from apps.asset.filters import AssetSearchFilter
from apps.utils.permissions import HRRequired

"""
Below Four(4) viewa describes the category details that are managed
"""


class AssetCategoryCreateView(HRRequired, CreateView):
    """For Creating New Categories"""
    template_name = "asset/asset_add_category.html"
    model = AssetCategory
    fields = ('name', 'count')

    def form_valid(self, form):
        return super(AssetCategoryCreateView, self).form_valid(form)

    def form_invalid(self, form):
        return super(AssetCategoryCreateView, self).form_invalid(form)

    def get_success_url(self):
        return reverse('asset:asset_category_list')


class AssetCategoryListView(HRRequired, ListView):
    """For listing already available categories"""
    template_name = "asset/asset_category_list.html"
    model = AssetCategory
    fields = ('name', 'count')
    paginate_by = 20


class AssetCategoryUpdateView(HRRequired, UpdateView):
    """For editing the Category details"""
    template_name = "asset/asset_category_update.html"
    model = AssetCategory
    fields = ('name', 'count')

    def get_context_data(self, **kwargs):
        return super(AssetCategoryUpdateView, self).get_context_data(**kwargs)

    def form_valid(self, form):
        return super(AssetCategoryUpdateView, self).form_valid(form)

    def form_invalid(self, form):
        return super(AssetCategoryUpdateView, self).form_invalid(form)

    def get_success_url(self):
        return reverse('asset:asset_category_list')


class AssetCategoryDeleteView(HRRequired, DeleteView):
    """For Removing Existing Assets"""
    model = AssetCategory

    def get_success_url(self):
        return reverse_lazy('asset:asset_list')


"""
Below Three(3) viewa describes the Asset details that are managed
"""


class AssetCreateView(HRRequired, CreateView):
    """For Creating New Assets"""
    template_name = "asset/asset_add.html"
    model = Component
    fields = ('category', 'name', 'code', 'price')

    def form_valid(self, form):
        return super(AssetCreateView, self).form_valid(form)

    def form_invalid(self, form):
        return super(AssetCreateView, self).form_invalid(form)

    def get_success_url(self):
        return reverse('asset:asset_list')


class AssetUpdateView(HRRequired, UpdateView):
    """For modifying existing Assets"""
    template_name = "asset/asset_update.html"
    model = Component
    fields = ('name', 'code', 'price', 'category')

    def get_context_data(self, **kwargs):
        return super(AssetUpdateView, self).get_context_data(**kwargs)

    def form_valid(self, form):
        return super(AssetUpdateView, self).form_valid(form)

    def form_invalid(self, form):
        return super(AssetUpdateView, self).form_invalid(form)

    def get_success_url(self):
        return reverse('asset:asset_list')


class AssetDeleteView(HRRequired, DeleteView):
    """For Removing Existing Assets"""
    model = Component

    def get_success_url(self):
        return reverse_lazy('asset:asset_list')


"""
Below Four(4) viewa describes the Asset ownership details that are managed
"""


class AssetListView(HRRequired, ListView):
    """ ListView for Assets that are created   """
    template_name = "asset/asset_list.html"
    model = Component
    allow_empty = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterdata'] = AssetSearchFilter(self.request.GET, Component.objects.
                                                  select_related('category').order_by('_is_defected', '-_is_vacant').all())
        page = self.request.GET.get('page', 1)

        paginator = Paginator(context['filterdata'].qs, 20)
        try:
            page_obj = paginator.page(page)
        except PageNotAnInteger:
            page_obj = paginator.page(1)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)
        context['filter'] = page_obj
        context['result'] = User.objects.filter(is_active=True).values('id', 'username')
        context['count_data'] = Component.objects.aggregate(unassign_count=Count('_is_vacant',
                                                                                 filter=Q(_is_vacant=True,
                                                                                          _is_defected=False)),
                                                            assign_count=Count('_is_vacant',
                                                                               filter=Q(_is_vacant=False,
                                                                                        _is_defected=False)),
                                                            damage_count=Count('_is_defected',
                                                                               filter=Q(_is_defected=True)))
        return context


class AssetAssign(HRRequired, UpdateView):
    """ UpdateView for assets to editing asset details"""
    template_name = "asset/asset_assign_list.html"
    model = Ownership
    form_class = AssignForm


@csrf_exempt
def ajax_asset_assign(request):
    """ Manage Assets to be Assigned """
    if request.method == "POST":
        asset_id = request.POST.get('component')
        user_id = request.POST.get('value')
        user = User.objects.get(id=user_id)
        asset_obj = Component.objects.get(id=asset_id)
        fromdate = datetime.datetime.now(tz=datetime.timezone.utc)
        asset_obj.assign_to(user, fromdate)
    return redirect('asset:asset_list')


@csrf_exempt
def ajax_asset_unassign(request):
    """ Manage Assets to be damaged """
    if request.method == "POST":
        asset_id = request.POST.get('element')
        asset_obj = Component.objects.get(id=asset_id)
        asset_obj.unassign_component()
    return redirect('asset:asset_list')


class AssetAssignListView(HRRequired, ListView):
    """
    ListView for Assets that are assigned to users
    Don't forgot to change paginate_by
    """
    template_name = "asset/asset_damaged.html"
    model = Ownership
    queryset = Ownership.objects.filter(defected=False).select_related('user', 'component__defected_by', 'component')
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['result'] = User.objects.filter(is_active=True).values('id', 'username')
        return context


@csrf_exempt
def ajax_asset_defected(request):
    """Marks assets as damaged"""
    if request.method == "POST":
        asset_id = request.POST.get('component')
        user_id = request.POST.get('value')
        user = User.objects.get(id=user_id)
        asset_obj = Component.objects.get(id=asset_id)
        asset_obj.mark_damaged_assets(user)
    return redirect('asset:asset_assign')


"""
Below is the function for defining the  
"""


class UserAssetListView(ListView):
    model = Ownership
    template_name = "asset/asset_user_listview.html"

    def get_queryset(self):
        queryset = Ownership.objects.select_related('component', 'user').filter(user=self.request.user.id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data'] = self.get_queryset()
        return context

apps/asset/templates/asset/asset_category_list.html
{% extends 'paper/layout.html'  %}
{% block title %} Asset List {% endblock %}
{% load static crispy_forms_tags %}
{% block content %}
<nav aria-label="breadcrumb" role="navigation" class="ml-3 mr-3">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active"><a href="{% url 'asset:asset_list' %}">Asset Home</a></li>
    <li class="breadcrumb-item active"><a href="{% url 'asset:asset_category_list' %}">Category List</a></li>
  </ol>
</nav>



<div class="row m-auto">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header with-border"><h3 class="box-title">Asset Category - List</h3>
                <div class="box-tools pull-right">
                    <!-- Buttons, labels, and many other things can be placed here! -->
                    <!-- Here is a label for example -->
                    <a href="{% url 'asset:asset_add_category' %}" class="btn btn-success">Add New Category</a>
                </div>
                <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="card-body col-md-11">
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Count</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    {% for types in object_list %}
                    <tbody>
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ types.name }}</td>
                        <td>{{ types.count }}</td>
                        <td>
                            <a href="{% url 'asset:asset_category_update' types.pk %}" type="submit" class="btn btn-primary btn-sm">Edit</a>
                        </td>
                    </tr>
                    </tbody>
                    {% endfor %}
                </table>
            </div>
            <!-- /.box-body -->
            <div class="card-footer">
                {% if is_paginated %}
                  <ul class="pagination  pg-blue">
                    {% if page_obj.has_previous %}
                      <li class="page-item "><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                      <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                      {% if page_obj.number == i %}
                        <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                      {% else %}
                        <li class="page-item "><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                      {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                      <li class="page-item "><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                      <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                    {% endif %}
                  </ul>
                {% endif %}
            </div>
            <!-- box-footer -->
        </div>

    </div>
</div>
{% endblock %}

apps/asset/templates/asset/asset_list.html
{% extends 'paper/layout.html'  %}
{% block title %} Asset List {% endblock %}
{% load static crispy_forms_tags %}
{% load templatehelpers %}
{% block content %}
<nav aria-label="breadcrumb" role="navigation" class="col-md-11">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href="{% url 'asset:asset_list' %}">Asset Home</a></li>
    </ol>
</nav>
<div class="row">
    <div class="col-md-9 ml-2">
        <div class="card">
            <div class="card-header with-border"><h1 class="card-title display-4">Asset List</h1>
                <div class="box-tools pull-right">
                    &nbsp;&nbsp;&nbsp;<a href="{% url 'asset:asset_category_list' %}" class="btn btn-primary">Asset
                    Category</a>
                    &nbsp;&nbsp;&nbsp;<a href="{% url 'asset:asset_add' %}" class="btn btn-success">Add Asset</a>
                    &nbsp;&nbsp;&nbsp;<a href="{% url 'asset:asset_assign' %}" class="btn btn-danger">Damaged Assets</a>
                </div>
                <!-- /.box-tools -->
            </div>
            <hr>
            <form method="get ">
                    &nbsp;&nbsp;&nbsp;
                <div class="row ml-2">
                    {% for field in filterdata.form %}
                    <div class="col-md-3">
                        {{field|as_crispy_field}}
                    </div>
                    {% endfor %}
                    <div class="col-md-3">
                          <button type="submit" class="btn btn-primary btn-sm " style="height:40px;margin-top:20px;">Search</button>
                    </div>

                </div>
                    <hr>
            </form>
            <!-- /.box-header -->
            <div class="card-body col-md-12">
                <table class="table">
                    <thead>
                    <tr class="text-center">
                        <th>#</th>
                        <th>Name</th>
                        <th>code</th>
                        <th>Type</th>
                        <th>Price</th>
                        <th>Assigned to</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    {% if filter %}
                    <tbody>
                    {% for component in filter %}
                    <tr class="text-center">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ component.name }}</td>
                        <td>{{ component.code }}</td>
                        <td>{{ component.category }}</td>
                        <td>{{ component.price }}</td>
                        {% if component.is_defected == False %}
                            {% if component.is_vacant %}
                            <td>-</td>
                            {% else %}
                            <td>{{ component.ownership_set.first.user }}</td>
                            {% endif %}
                        <td class="row justify-content-center">
                            <a href="{% url 'asset:asset_update' component.id %}" type="submit"
                               class="btn btn-primary btn-sm ">Edit</a>

                            {% if component.is_vacant %}
                            &nbsp;&nbsp;
                            <form action="{% url 'asset:asset_remove' component.id %}" method="post">
                                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                            </form>
                            &nbsp;&nbsp;
                            <a type="submit" id="assign_btn" class="assign_btn btn btn-info btn-sm"
                               data-id="{{ component.id }}">Assign</a>
                            {% else %}

                            &nbsp;&nbsp;
                            <a type="submit" data-id="{{ component.id }}" class="unassign_btn btn btn-info btn-sm"
                               id="unassign_btn">UnAssign</a>
                            {% endif %}
                        </td>
                        {% else %}
                        <td>Damaged</td>
                        <td>
                            <form action="{% url 'asset:asset_remove' component.id %}" method="post">
                                 <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                            </form>
                        </td>
                        {% endif %}
                    </tr>
                    {% empty %}
                    <tr class="text-center">
                        <td colspan="7"><h3>No Components match your search criteria</h3></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                    {% endif %}
                </table>
            </div>
            <!-- /.box-body -->
            <div class="card-footer">
                {% if filter.has_other_pages %}
                <ul class="pagination  pg-blue">
                    {% if filter.has_previous %}
                    <li class="page-item "><a class="page-link"
                                              href="?page={{ filter.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                    <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                    {% endif %}
                    {% for i in filter.paginator.page_range %}
                    {% if filter.number == i %}
                    <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span>
                    </li>
                    {% else %}
                    <li class="page-item "><a class="page-link" href="{% relative_url i 'page' request.GET.urlencode %}">{{ i }}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if filter.has_next %}
                    <li class="page-item "><a class="page-link" href="{% relative_url filter.next_page_number 'page' request.GET.urlencode %}">&raquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
            <!-- box-footer -->
        </div>

    </div>
    <div class="col-lg-2 col-sm-2 ">
    <button type="button" class="btn btn-primary btn-lg">Assets Remaining&nbsp;<span class="badge bg-danger ms-2 " style="font-size:1rem;">{{ count_data.unassign_count }}</span>
    </button>
    <button type="button" class="btn btn-primary btn-lg">
        Assets Assigned &nbsp;&nbsp;<span class="badge bg-danger ms-2 " style="font-size:1rem;">{{ count_data.assign_count }}</span>
    </button>
    <button type="button" class="btn btn-primary  btn-lg">
        Assets Damaged  &nbsp;<span class="badge bg-danger ms-2 " style="font-size:1rem;">{{ count_data.damage_count }}</span>
    </button>
    </div>
</div>
{% endblock %}

{% block extra_javascript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.17/sweetalert2.min.js"
        integrity="sha512-Kyb4n9EVHqUml4QZsvtNk6NDNGO3+Ta1757DSJqpxe7uJlHX1dgpQ6Sk77OGoYA4zl7QXcOK1AlWf8P61lSLfQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
var elements = document.querySelectorAll(".unassign_btn");
function myFunction(event){
    var element = event.target.getAttribute('data-id') ;
    var DataJSON = { element:element }
Swal.fire({
      title: 'Are you sure?',
      text: "You want to unassign this asset!",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085D6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yes, Unassign!'
    }).then((result) => {
                if (result.isConfirmed) {
                        console.log(element);
                        $.ajax({
                                url  : "{% url 'asset:asset_unassign' %}",
                                method : 'post',
                                data : DataJSON,
                                success:function(data){
                                   Swal.fire(
                                  'Unassigned!',
                                  'Asset has been Unassigned.',
                                  'success').then(function(){
                                    location.reload()
                                    })
                                }
                        });
                }
       })
    }
    for( var i = 0 ; i < elements.length; i++ )
    {
        elements[i].addEventListener('click', myFunction )
    }

</script>
<script>
$(".assign_btn").on("click",async function(e) {
        e.preventDefault();
        var component=e.target.getAttribute('data-id')
        const { value: user } = await Swal.fire({
              title: 'Select User',
              input: 'select',
              inputOptions: {
                            {% for i in result %}
                              '{{ i.id }}': '{{ i.username }}',
                            {% endfor %}
                            },
              inputPlaceholder: 'Select a User',
              showCancelButton: true,
              inputValidator: (value) => {
                    return new Promise((resolve) => {
                      if (value !== '') {
                            console.log(value);
                            $.ajax({
                                url  : "{% url 'asset:asset_assign_ownership' %}",
                                method : 'post',
                                data : { value:value, component:component },
                                success:function(data){
                                   Swal.fire(
                                  'Unassigned!',
                                  'Asset has been Unassigned.',
                                  'success').then(function(){
                                    location.reload()
                                    })
                                }
                            });
                        resolve()
                      } else {
                        resolve('You need to select user :)')
                      }
            location.reload()
                    })

              }

        })
})
</script>
{% endblock %}