apps/leave/urls.py
from django.urls import path, include

from apps.leave.views import *

app_name = 'leave'


urlpatterns = [
    path('leaves/', include([
        path('', LeaveRequestListView.as_view(), name="list"),
        path('<int:pk>/view/', LeaveRequestDetailView.as_view(), name="view"),
        path('holidays/', HolidayListView.as_view(), name="holiday-list"),
        path('monthly-user-leaves/', UserLeaveView.as_view(), name="user-leave"),
        path('annual-user-leaves/', UserAnnualLeaveView.as_view(), name="annual-user-leave"),
        path('new-requests/', NewLeaveRequestsListView.as_view(), name="new-leave-requests"),
        path('new-requests/<int:pk>/modify/', NewLeaveRequestsDetailView.as_view(), name="detail"),

    ])),
    path('wfh/', include([
        path('', WFHRequestListView.as_view(), name="wfh-list"),

        path('requests/', WFHListView.as_view(), name="wfh-hr-list"),
        path('requests/<int:pk>/approve/', WFHUpdateView.as_view(), name="wfh-hr-update"),
    ])),
    path('late-attendance/', include([
        path('', LateAttendanceListView.as_view(), name="late-attendance-list"),
    ])),
]

apps/payslip/urls.py
from django.shortcuts import render
from django.urls import path, include, reverse_lazy
from django.views.generic import DeleteView

from apps.payslip.models import MonthlyPaymentSummery, AttendanceData
from apps.payslip.views import PaySlipList, AttendanceDataUpdate, PayslipDetail, \
    GeneratePdf, payslip_details_for_account, AttendanceDataList

app_name = 'payslip'

api_urlpatterns = []


def template_preview(request):
    from apps.accounts.models import ProformaInvoice
    cxt = {
        'object': ProformaInvoice.objects.order_by('id').first()
    }
    return render(request, template_name='accounts/proforma-invoice-templates.html', context=cxt)


urlpatterns = [
    path('view/', template_preview),
    path('payslip/', include([
        path('', PaySlipList.as_view(), name="payslip-list"),
        path('<int:pk>/detail/', PayslipDetail.as_view(), name="payslip-detail"),
        path('<int:pk>/detail-sheet.xlsx', payslip_details_for_account, name="payslip-sheet"),

        # path('<int:pk>/update/', PaySlipUpdate.as_view(), name="payslip-update"),
        path('<int:pk>/delete/', DeleteView.as_view(
            model=MonthlyPaymentSummery, success_url=reverse_lazy("payslip:payslip-list")
        ), name="payslip-delete"),
        path('attendance/<int:pk>/view/', AttendanceDataUpdate.as_view(), name="attendance-update"),
        path('attendance/<int:pk>/download/', GeneratePdf.as_view(), name="attendance-download"),

        # Common view to list all of my payslip
        path('all/', AttendanceDataList.as_view(), name="payslip-my-list"),
    ]))
]

apps/petty/urls.py
from django.urls import path, include

from apps.petty.api import PettyViewSet
from apps.petty.views import PettyList, PettyUpdate, export_petty_xls

app_name = 'petty'

petty_list = PettyViewSet.as_view({'get': 'list', 'post': 'create'})
petty_detail = PettyViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update', 'put': 'update', 'delete': 'destroy'})


api_urlpatterns = [
    path('petty/<int:month>/<int:year>/', petty_list, name="petty-list"),
    path('petty/<int:pk>/', petty_detail, name="petty-detail"),
]


urlpatterns = [
    path('petty/', PettyList.as_view(), name="dashboard-petty"),
    path('petty/<int:month>/<int:year>/download/excel', export_petty_xls, name="download-petty-excel"),
    path('petty/<int:pk>/', PettyUpdate.as_view(), name="dashboard-petty-detail"),
    path('api/v1/', include(api_urlpatterns)),
]

apps/project/urls.py
from django.urls import path, include

from apps.project.views import (
    ProjectListView, ProjectCreateView, ProjectUpdateView, ProjectActivationView,
    ClientListView, ClientCreateView, ClientUpdateView, HostingListView, HostingCreateView, HostingUpdateView,
    BillingStatusCreateView, BillingStatusDeleteView, ProspectCreateView, ProspectDeleteView, InflowListView,
    InflowUpdateView, InflowDetailView, BranchUpdateView, BranchDeleteView
)

app_name = "project"

urlpatterns = [
    path('project/', include([
        path('', ProjectListView.as_view(), name="project-list"),
        path('create/', ProjectCreateView.as_view(),
             name="project-create"),
        path('<int:pk>/update/', ProjectUpdateView.as_view(),
             name="project-update"),
        path('<int:pk>/activation/', ProjectActivationView.as_view(),
             name="project-activation"),
    ])),
    path('project/client/', include([
        path('', ClientListView.as_view(), name="client-list"),
        path('create/', ClientCreateView.as_view(),
             name="client-create"),
        path('<int:pk>/update/', ClientUpdateView.as_view(),
             name="client-update"),
    ])),
    path('project/hosting/', include([
        path('', HostingListView.as_view(), name="hosting-list"),
        path('create/', HostingCreateView.as_view(),
             name="hosting-create"),
        path('<int:pk>/update/', HostingUpdateView.as_view(),
             name="hosting-update"),
    ])),
    path('project/billing/', include([
        path('', BillingStatusCreateView.as_view(), name="create_billing"),
        path('update/<int:pk>/', BillingStatusCreateView.as_view(), name="update_billing"),
        path('delete/<int:pk>/', BillingStatusDeleteView.as_view(), name="delete_billing"),
    ])),
    path('project/prospects/', include([
        path('', ProspectCreateView.as_view(), name="create_prospect"),
        path('update/<int:pk>/', ProspectCreateView.as_view(), name="update_prospect"),
        path('delete/<int:pk>/', ProspectDeleteView.as_view(), name="delete_prospect"),
    ])),
    path('project/inflow-outflow/', include([
        path('', InflowListView.as_view(), name="inflow_list"),
        path('update/<int:pk>/', InflowUpdateView.as_view(), name="inflow_update"),
        path('detail/<int:pk>/', InflowDetailView.as_view(), name="inflow_detail"),
        # path('delete/<int:pk>/', InflowDeleteView.as_view(), name="inflow_delete"),
    ])),
    path('project/branch/', include([
        path('', BranchUpdateView.as_view(), name="branch_list"),
        path('update/<int:pk>/', BranchUpdateView.as_view(), name="branch_update"),
        path('delete/<int:pk>/', BranchDeleteView.as_view(), name="branch_delete"),
    ]))
]

fims/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin, messages
from django.shortcuts import redirect
from django.urls import path, include, reverse
import debug_toolbar
from django.conf.urls import url

from rest_auth.views import (
    LogoutView, UserDetailsView, PasswordChangeView,
    PasswordResetView, PasswordResetConfirmView
)
from apps.generic.login import LoginView as APILoginView

from apps.generic.index import HomeView, trigger_error, LoginView as WebLoginView
from apps.root import root


def redirect_to_login(request):
    """
    this view is used to disable allauth signup which redirects on failed social login;
    redirect it to settings.LOGIN_URL
    """
    messages.warning(request, "No account found with the registered email address.")
    return redirect(reverse(settings.LOGIN_URL))


urlpatterns = [
    path('fegnomin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    # path('login/', LoginView.as_view(), name='login'),
    path('login/', WebLoginView.as_view(template_name="paper/login.html"), name='login'),
    path('', HomeView.as_view(), name="dashboard-index"),
    # path('', login_required(RedirectView.as_view(pattern_name='leave:list')), name="dashboard-index"),
    path('', include("apps.accounts.urls")),
    path('', include("apps.asset.urls")),
    path('', include("apps.documents.urls")),
    path('', include("apps.leave.urls")),
    path('', include("apps.petty.urls")),
    path('', include("apps.project.urls")),
    path('', include("apps.user.urls")),
    path('', include("apps.payslip.urls")),
    path('sop/', include("apps.sop.urls")),
    path('', include("apps.drar.urls")),
    path('api/v1/bcard/', include("apps.bcard")),
    path('careers/recruitment/', include("apps.recruitment.urls")),
    path('api/v1/', root, name="root"),
    path('api/v1/', include('apps.leave.api_urls')),

    # path(r'nda-agreed-contents/', include('private_files.urls')),
    path('sentry-debug/', trigger_error),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/social/signup/', redirect_to_login, name="socialaccount_signup"),
    path('accounts/', include('allauth.urls')),

    path('rest-auth/', include([
        # URLs that do not require a session or valid token
        url(r'^password/reset/$', PasswordResetView.as_view(),
            name='rest_password_reset'),
        url(r'^password/reset/confirm/$', PasswordResetConfirmView.as_view(),
            name='rest_password_reset_confirm'),
        url(r'^login/$', APILoginView.as_view(), name='rest_login'),
        # URLs that require a user to be logged in with a valid session / token.
        url(r'^logout/$', LogoutView.as_view(), name='rest_logout'),
        url(r'^user/$', UserDetailsView.as_view(), name='rest_user_details'),
        url(r'^password/change/$', PasswordChangeView.as_view(),
            name='rest_password_change'),
    ])),
    # path('base.html', TemplateView.as_view(template_name="paper/layout.html")),
    # path('dashboard.html', TemplateView.as_view(template_name="paper/examples/dashboard.html")),
    # path('icons.html', TemplateView.as_view(template_name="paper/examples/icons.html")),
    # path('notifications.html', TemplateView.as_view(template_name="paper/examples/notifications.html")),
    # path('tables.html', TemplateView.as_view(template_name="paper/examples/tables.html")),
    # path('typography.html', TemplateView.as_view(template_name="paper/examples/typography.html")),
    # path('user.html', TemplateView.as_view(template_name="paper/examples/user.html")),
    path('baton/', include('baton.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]


if settings.DEBUG:
    urlpatterns.extend([
        *static(settings.STATIC_URL, document_root=os.path.join(settings.BASE_DIR, settings.STATICFILES_DIRS[0])),
        *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    ])

templates/adminlte/lib/_admin_sidebar.html
<li class="treeview" >
    <a href="#">
        <i class="fa fa-group"></i> <span>Administration</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-right pull-right"></i>
        </span>
    </a>
    <ul class="treeview-menu">
        <li>
            <a href="{% url 'admin:index' %}" target="_blank">
                <i class="fa fa-dashboard"></i>  Admin Panel
            </a>
        </li>
        {% if request.user.is_manager %}
        <li >
            <a href="{% url 'petty:dashboard-petty' %}">
                <i class="fa fa-th-list" aria-hidden="true"></i> <span>Petty</span>
            </a>
        </li>
        {% endif %}
    </ul>
</li>

templates/adminlte/lib/_main_footer.html
{% extends 'adminlte/lib/_main_footer.html'  %}

templates/adminlte/lib/_main_header.html
{% extends 'adminlte/lib/_main_header.html'  %}
{% load static i18n %}
{% block logo_text %}<img  src="{% static 'images/fegno-logo-white-text.png' %}" height="36px" alt="fegno logo" />{% endblock %}

{% block logo_text_small %}<img src="{% static 'images/fegno.png' %}" height="24px" alt="logo favicon" /> {% endblock %}

{% block logout_url %}{% url 'logout' %}{% endblock %}

{% block change_password_url %}{% url 'password_change' %}{% endblock %}


{% block header_dropdowns %}
{% if request.user.is_authenticated %}
<li class="dropdown user user-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <img src="{{ request.user.avatar_url }}" class="user-image" alt="User Image">
        <span class="hidden-xs">{% firstof request.user.get_short_name request.user.get_username %}</span>
    </a>
    <ul class="dropdown-menu">
        {% block user_header %}
        <li class="user-header">
            <img src="{{ request.user.avatar_url }}" class="img-circle" alt="User Image">
            <p>
                {% firstof request.user.get_short_name request.user.get_username %}
                <small>Member since {{ request.user.date_joined }}</small>
            </p>
        </li>
        {% endblock %}

        <!-- Menu Footer-->
        {% block menu_footer %}
        <li class="user-footer">
            <div class="pull-left">
                <a href="{% url 'password_change' %}"
                   class="btn btn-default btn-flat">{% trans 'Change password' %}</a>
            </div>
            <div class="pull-right">
                <a href="{% url 'logout' %}" class="btn btn-default btn-flat">Sign out</a>
            </div>
        </li>
        {% endblock %}

    </ul>
</li>
{% endif %}
{% endblock header_dropdowns %}

templates/adminlte/lib/_main_sidebar.html
<!--{% extends 'adminlte/lib/_main_sidebar.html'  %}-->


{% block nav_links_ul %}
<ul class="nav">
    {% block nav_links_outer %}
    <li class="header">{% block nav_heading %}MAIN NAVIGATION{% endblock %}</li>

    {% block nav_links %}
    <li>
        <a href="{% url 'leave:holiday-list' %}">
            <i class="fa fa-calendar-check-o"></i> <span>Holidays</span>
        </a>
    </li>
    <li>
        <a href="{% url 'leave:list' %}">
            <i class="fa fa-sign-out" aria-hidden="true"></i><span>Leaves</span>
        </a>
    </li>
    <li>
        <a href="{% url 'documents:circular-list' %}">
            <i class="fa fa-newspaper-o" aria-hidden="true"></i><span>Circulars</span>
        </a>
    </li>
    <li>
        <a href="{% url 'documents:publicdocuments-list' %}">
            <i class="fa fa-braille" aria-hidden="true"></i><span>Policy documents</span>
        </a>
    </li>
    {% if not request.user.is_manager %}
    <li>
        <a href="{% url 'payslip:payslip-my-list' %}">
            <i class="fa fa-book" aria-hidden="true"></i><span>PaySlips</span>
        </a>
    </li>
    {% endif %}
    <li>
        <a href="{% url 'documents:userdocuments-list' %}">
            <i class="fa fa-book" aria-hidden="true"></i><span>My Documents</span>
        </a>
    </li>
    {% include 'paper/utils/_user_permission_menus.html' %}
    {% if user.is_superuser %}
    {% include 'paper/utils/admin_menu.html' %}
    {% endif %}
    {% endblock nav_links %}
    {% endblock nav_links_outer %}
</ul>
{% endblock nav_links_ul %}

templates/adminlte/lib/_select2_assets.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw==" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.full.min.js" integrity="sha512-RtZU3AyMVArmHLiW0suEZ9McadTdegwbgtiQl5Qqo9kunkVg1ofwueXD8/8wv3Af8jkME3DDe3yLfR8HSJfT2g==" crossorigin="anonymous"></script>
<script>
    $(document).ready(function() {
        $('select.select2').select2();
    });
</script>

templates/adminlte/lib/_user_permission_menus.html
{% load py_utils %}

++++++++++++++++++++++++++++++++++ NOT USING ++++++++++++++++++++++++++++++++++

{% if request.user.is_devops %}
<li>
    <a href="#"><i class="fa fa-code"></i> <span>Devops</span><span class="pull-right-container"><i class="fa fa-angle-right pull-right"></i></span></a><ul class="treeview-menu">
    <li>
        <a href="{% url 'project:hosting-list' %}">
            <i class="fa fa-clone"></i> Hosting List
        </a>
    </li>

</ul></li>
{% endif %}

{% if request.user.is_in_business %}
<li>
    <a href="#"><i class="fa fa-group"></i> <span>Business</span><span class="pull-right-container"><i class="fa fa-angle-right pull-right"></i></span></a><ul class="treeview-menu">
    <li>
        <a href="{% url 'project:project-list' %}">
<!--            <i class="fa fa-hdd-o"></i> -->
            Projects & Clients
        </a>
    </li>
    <li >
        <a href="{% url 'accounts:proforma-list' %}">
<!--            <i class="fa fa-th-list" aria-hidden="true"></i> -->
            <span>Proforma </span>
        </a>
    </li>

</ul></li>
{% endif %}

{% if request.user.is_hr %}
{% no_of_pending_leaves as pending_leaves %}
<li class="treeview" >
    <a href="#">
        <i class="fa fa-group"></i>
        <span> HR  </span>
        <span class="pull-right-container"><i class="fa fa-angle-right pull-right"></i></span></a>
    <ul class="treeview-menu">
    <li>
        <a href="{% url 'leave:new-leave-requests' %}">
<!--            <i class="fa fa-bars"></i> -->
            {% if pending_leaves%} <span class="label bg-yellow">{{ pending_leaves }}</span>   New Requests {% endif %}
        </a>
    </li>
    <li>
        <a href="{% url 'payslip:payslip-list' %}">
<!--            <i class="fa fa-ellipsis-v"></i>  -->
            Payslip List
        </a>
    </li>
    <li>
        <a href="{% url 'leave:annual-user-leave' %}">
<!--            <i class="fa fa-building"></i>  -->
            Annual Summery
        </a>
    </li>
    <li>
        <a href="{% url 'leave:user-leave' %}">
<!--            <i class="fa fa-calendar-check-o"></i>  -->
            Month Summery
        </a>
    </li>
    <li>
        <a href="{% url 'leave:late-attendance-list' %}">
<!--            <i class="fa fa-calendar-times-o"></i>  -->
            Late Attendance
        </a>
    </li>
</ul></li>

{% endif %}