apps/project/urls.py
from django.urls import path, include

from apps.project.views import (
    ProjectListView, ProjectCreateView, ProjectUpdateView, ProjectActivationView,
    ClientListView, ClientCreateView, ClientUpdateView, HostingListView, HostingCreateView, HostingUpdateView,
    BillingStatusCreateView, BillingStatusDeleteView, ProspectCreateView, ProspectDeleteView, InflowListView,
    InflowUpdateView, InflowDetailView, BranchUpdateView, BranchDeleteView
)

app_name = "project"

urlpatterns = [
    path('project/', include([
        path('', ProjectListView.as_view(), name="project-list"),
        path('create/', ProjectCreateView.as_view(),
             name="project-create"),
        path('<int:pk>/update/', ProjectUpdateView.as_view(),
             name="project-update"),
        path('<int:pk>/activation/', ProjectActivationView.as_view(),
             name="project-activation"),
    ])),
    path('project/client/', include([
        path('', ClientListView.as_view(), name="client-list"),
        path('create/', ClientCreateView.as_view(),
             name="client-create"),
        path('<int:pk>/update/', ClientUpdateView.as_view(),
             name="client-update"),
    ])),
    path('project/hosting/', include([
        path('', HostingListView.as_view(), name="hosting-list"),
        path('create/', HostingCreateView.as_view(),
             name="hosting-create"),
        path('<int:pk>/update/', HostingUpdateView.as_view(),
             name="hosting-update"),
    ])),
    path('project/billing/', include([
        path('', BillingStatusCreateView.as_view(), name="create_billing"),
        path('update/<int:pk>/', BillingStatusCreateView.as_view(), name="update_billing"),
        path('delete/<int:pk>/', BillingStatusDeleteView.as_view(), name="delete_billing"),
    ])),
    path('project/prospects/', include([
        path('', ProspectCreateView.as_view(), name="create_prospect"),
        path('update/<int:pk>/', ProspectCreateView.as_view(), name="update_prospect"),
        path('delete/<int:pk>/', ProspectDeleteView.as_view(), name="delete_prospect"),
    ])),
    path('project/inflow-outflow/', include([
        path('', InflowListView.as_view(), name="inflow_list"),
        path('update/<int:pk>/', InflowUpdateView.as_view(), name="inflow_update"),
        path('detail/<int:pk>/', InflowDetailView.as_view(), name="inflow_detail"),
        # path('delete/<int:pk>/', InflowDeleteView.as_view(), name="inflow_delete"),
    ])),
    path('project/branch/', include([
        path('', BranchUpdateView.as_view(), name="branch_list"),
        path('update/<int:pk>/', BranchUpdateView.as_view(), name="branch_update"),
        path('delete/<int:pk>/', BranchDeleteView.as_view(), name="branch_delete"),
    ]))
]

fims/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin, messages
from django.shortcuts import redirect
from django.urls import path, include, reverse
import debug_toolbar
from django.conf.urls import url

from rest_auth.views import (
    LogoutView, UserDetailsView, PasswordChangeView,
    PasswordResetView, PasswordResetConfirmView
)
from apps.generic.login import LoginView as APILoginView

from apps.generic.index import HomeView, trigger_error, LoginView as WebLoginView
from apps.root import root


def redirect_to_login(request):
    """
    this view is used to disable allauth signup which redirects on failed social login;
    redirect it to settings.LOGIN_URL
    """
    messages.warning(request, "No account found with the registered email address.")
    return redirect(reverse(settings.LOGIN_URL))


urlpatterns = [
    path('fegnomin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    # path('login/', LoginView.as_view(), name='login'),
    path('login/', WebLoginView.as_view(template_name="paper/login.html"), name='login'),
    path('', HomeView.as_view(), name="dashboard-index"),
    # path('', login_required(RedirectView.as_view(pattern_name='leave:list')), name="dashboard-index"),
    path('', include("apps.accounts.urls")),
    path('', include("apps.asset.urls")),
    path('', include("apps.documents.urls")),
    path('', include("apps.leave.urls")),
    path('', include("apps.petty.urls")),
    path('', include("apps.project.urls")),
    path('', include("apps.user.urls")),
    path('', include("apps.payslip.urls")),
    path('sop/', include("apps.sop.urls")),
    path('', include("apps.drar.urls")),
    path('api/v1/bcard/', include("apps.bcard")),
    path('careers/recruitment/', include("apps.recruitment.urls")),
    path('api/v1/', root, name="root"),
    path('api/v1/', include('apps.leave.api_urls')),

    # path(r'nda-agreed-contents/', include('private_files.urls')),
    path('sentry-debug/', trigger_error),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/social/signup/', redirect_to_login, name="socialaccount_signup"),
    path('accounts/', include('allauth.urls')),

    path('rest-auth/', include([
        # URLs that do not require a session or valid token
        url(r'^password/reset/$', PasswordResetView.as_view(),
            name='rest_password_reset'),
        url(r'^password/reset/confirm/$', PasswordResetConfirmView.as_view(),
            name='rest_password_reset_confirm'),
        url(r'^login/$', APILoginView.as_view(), name='rest_login'),
        # URLs that require a user to be logged in with a valid session / token.
        url(r'^logout/$', LogoutView.as_view(), name='rest_logout'),
        url(r'^user/$', UserDetailsView.as_view(), name='rest_user_details'),
        url(r'^password/change/$', PasswordChangeView.as_view(),
            name='rest_password_change'),
    ])),
    # path('base.html', TemplateView.as_view(template_name="paper/layout.html")),
    # path('dashboard.html', TemplateView.as_view(template_name="paper/examples/dashboard.html")),
    # path('icons.html', TemplateView.as_view(template_name="paper/examples/icons.html")),
    # path('notifications.html', TemplateView.as_view(template_name="paper/examples/notifications.html")),
    # path('tables.html', TemplateView.as_view(template_name="paper/examples/tables.html")),
    # path('typography.html', TemplateView.as_view(template_name="paper/examples/typography.html")),
    # path('user.html', TemplateView.as_view(template_name="paper/examples/user.html")),
    path('baton/', include('baton.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]


if settings.DEBUG:
    urlpatterns.extend([
        *static(settings.STATIC_URL, document_root=os.path.join(settings.BASE_DIR, settings.STATICFILES_DIRS[0])),
        *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    ])

apps/project/models.py
from datetime import datetime
from django.db import models
from gst_field.modelfields import GSTField
from phonenumber_field.modelfields import PhoneNumberField

from apps.generic.models.address import AddressAbstract
from apps.user.models import User
from fims import settings


class Client(AddressAbstract, models.Model):
    name = models.CharField(max_length=256)
    gst_in = GSTField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=256)
    short_code = models.CharField(max_length=4, verbose_name="Short Code")
    client = models.ForeignKey(Client, on_delete=models.CASCADE, )
    concern_person = models.CharField(max_length=256, null=True, blank=True)
    concern_number = PhoneNumberField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    @property
    def state(self):
        return 'Activated' if self.is_active else 'Closed'

    def __str__(self):
        return self.name


class HostingService(models.Model):
    name = models.CharField(max_length=256)
    service_provider = models.CharField(max_length=256)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, blank=True)
    date_of_hosting = models.DateField()
    date_of_expiry = models.DateField()
    amount = models.FloatField(null=True)

    def __str__(self):
        return self.name



"""
Below contains models  created for business related prospects and Billing status
"""


class BillingStatus(models.Model):
    STATE_CHOICES = [
        ('SALES', 'SALES'),
        ('DEVELOPMENT', 'DEVELOPMENT'),
        ('AMC', 'AMC')
    ]
    name = models.CharField(max_length=255)
    state = models.CharField(max_length=255, choices=STATE_CHOICES)
    display_order = models.IntegerField(default=20)

    class Meta:
        ordering = ('display_order',)

    def __str__(self):
        return self.name


class Prospect(models.Model):
    name = models.CharField(max_length=255, help_text="Project or client name")
    amount = models.FloatField(null=True, blank=True)
    status = models.ForeignKey(BillingStatus, on_delete=models.CASCADE, null=True, blank=True)
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateField(auto_now_add=True)
    target_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-id',)

apps/project/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, DateField, DateInput, ChoiceField
from django.utils.datetime_safe import date


from apps.accounts.models import month_validation, year_validation, InflowOutflow
from apps.payslip.utils.calender import CALENDER
from apps.project.models import Prospect
from apps.utils.forms import BootstrapFormMixin


class DatePickerInput(DateInput):
    input_type = 'date'


class ProspectForm(ModelForm):
    target_date = DateField(
        widget=DatePickerInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Prospect
        fields = ('name', 'amount', 'assigned_to', 'status', 'target_date')


class InflowOutflowGenerator(BootstrapFormMixin, ModelForm):
    class Meta:
        model = InflowOutflow
        fields = ('month', 'year')

    month = ChoiceField(choices=CALENDER.MONTHS, validators=[month_validation])
    year = ChoiceField(choices=[(i, i) for i in range(date.today().year+1, date.today().year-1, -1)],
                       validators=[year_validation])

    def clean_month(self):
        return int(self.cleaned_data['month'])

    def clean_year(self):
        return int(self.cleaned_data['year'])

    def clean(self):
        cleaned_data = self.cleaned_data
        cleaned_year = int(cleaned_data['year'])
        cleaned_month = int(cleaned_data['month'])
        exists = InflowOutflow.objects.filter(year=cleaned_year, month=cleaned_month).exists()
        InflowOutflow.objects.get_or_create(year=int(cleaned_data['year']), month=int(cleaned_data['month']))
        if exists:
            raise ValidationError("Inflow Outflow already Generated")
        return cleaned_data


class InflowOutflowUpdateViewForm(ModelForm):
    class Meta:
        model = InflowOutflow
        exclude = ('month','year',)

apps/project/templates/project/billing_create.html
{% extends 'paper/layout.html'  %}
{% block title %}  {% endblock %}
{% load static crispy_forms_tags %}
{% block content %}
{% block navpage %}
<nav aria-label="breadcrumb" role="navigation" class="col-md-8 ml-1 mr-4">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active"><a href="{% url 'project:create_prospect' %}">Prospect Home</a></li>
  <li class="breadcrumb-item active"><a href="{% url 'project:create_billing' %}">BIlling status</a></li>
  </ol>
</nav>
{% endblock %}
<div class="row">
    <div class="col-md-8">
        <div class="card ml-2 p-4">
            <div class="card-body">
                                <h4>Billing Status List</h4>
                <hr/>
                {% if object_list %}
                <table class="table">
                    <thead>
                    <tr class="text-center">
                        <th>#</th>
                        <th>Name</th>
                        <th>State</th>
                        <th>Display Order</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for project in object_list %}
                    <tr class="text-center">
                        <td>{{forloop.counter}}</td>
                        <td>{{project.name}}</td>
                        <td>{{project.state}}</td>
                        <td>{{project.display_order}}</td>
                        <td class="text-center d-flex justify-content-center">
                            <a class="btn btn-info btn-sm" href="{% url 'project:update_billing' project.pk %}">Edit</a>
                            <form action="{% url 'project:delete_billing' project.pk %}" method="post">
                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                            </form>
                        </td>

                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <h5>No Records Found...!</h5>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card mr-2 ml-2 p-4">
            <div class="card-body">
                <h4>Billing Status</h4>
                <hr/>
                <form method="post">
                    {% csrf_token %}
                    <div class="col-md-12 form-group pb-5">
                        {{ form|crispy }}
                    </div>
                    <hr>
                    <div class="">
                        <button class="btn btn-success">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

apps/project/templates/project/branch_create_list.html
{% extends 'project/inflow_outflow_list.html'  %}

{% block pg-header %}Branch{% endblock %}
{% block pg-header2 %}Branch List{% endblock %}
{% block branchbutton %}{% endblock %}
{% block thead %}
<thead>
<tr class="text-center">
    <th>#</th>
    <th>Branch Name</th>
    <th>Action</th>
</tr>
</thead>

{% endblock %}
{% block tbody %}
<tbody>
{% for data in object_list %}
<tr class="text-center">
    <td>{{forloop.counter}}</td>
    <td>{{data.name}}<br></td>
    <td class="text-center d-flex justify-content-center">
        <a class="btn btn-info btn-sm"
           href="{% url 'project:branch_update' data.pk %}">Edit</a>
        <form action="{% url 'project:branch_delete' data.pk %}" method="post">
            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
        </form>
    </td>
</tr>
{% empty %}
<tr class="text-center">
    <td colspan="7"><h3>No datas found</h3></td>
</tr>
{% endfor %}
</tbody>

{% endblock %}

apps/project/templates/project/client_list.html
{% extends 'paper/layout.html'  %}
{% load static %}
{% block title %} Client | Project Management | {{ block.super }}{% endblock %}

{% block content %}
<div class="card card-default "  id="app">
    <div class="card-header card-header-danger">
        <h4> Clients </h4>
      <div class="box-tools pull-right">
        <a href="{% url 'project:client-create' %}" class="btn btn-success btn-sm">Create new Project</a>
      </div>

    </div>
    <hr />

    <div class="card-body">
        <h4>Clients.</h4>
        {% if object_list %}
        <div class="table-responsive">
            <table class="table table-bordered ">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Contact Number</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for client in object_list %}
                <tr>
                    <td>{{ client.id }}</td>
                    <td>{{ client.name }}</td>
                    <td>{{ client.contact_01 }}</td>
                    <td><a href="{% url 'project:client-update' pk=client.pk %}" class="btn btn-sm btn-primary">View</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    </div>
    <div class="card-footer clearfix">
        {% include 'adminlte/lib/_pagination.html' %}
    </div>
</div>
<script>
    (function(){
        {% if messages %}
        {% for message in messages %}
            swal("{% if message.tags %}{{ message.tags }}{% endif %}", "{{ message|safe }}", "{% if message.tags %}{{ message.tags }}{% endif %}");
        {% endfor %}
        {% endif %}
    })()
    </script>
{% endblock %}


{% block javascript %}
{% include 'adminlte/lib/_scripts.html' %}
<script>
</script>
{% endblock %}

apps/project/templates/project/hostingservice_form.html
{% extends 'paper/layout.html'  %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Hosting Services | Project Management | {{ block.super }}{% endblock %}

{% block stylesheets %}
{% include 'adminlte/lib/_styles.html' %}
<style>.unselectable {-webkit-touch-callout: none;-webkit-user-select: none;-khtml-user-select: none;-moz-user-select: none;-ms-user-select: none;user-select: none;} </style>
{% endblock %}

{% block content %}
<div class="card " id="app">
    <div class="card-header card-header-danger">
      {% if object.pk %}
        <h3>Update Project - {{ object.name }}</h3>
      {% else %}
        <h3>Create Project</h3>
      <div class="box-tools pull-right">
        <a href="{% url 'project:client-create' %}" class="btn btn-success btn-sm">Create new Client</a>
      </div>
      {% endif %}

    </div>
    <div class="card-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-7">
                    <form method="POST" enctype="multipart/form-data" >
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary " >Save</button>
                    </form>
                    {% if object.pk and object.client_id %}
                        <a href="{% url 'project:client-update' pk=object.client.pk %}" class="btn btn-sm btn-secondary">Change Client Data</a>
                    {% endif %}
                </div>
            </div>
            <hr />
        </div>
    </div>
    <div class="card-footer clearfix">
    </div>
</div>
{% endblock %}


{% block extra_foot %}
<style>.helptext{color:#777; font-size:smaller; display:block;}</style>
<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker3.standalone.min.css' %}" integrity="sha512-p4vIrJ1mDmOVghNMM4YsWxm0ELMJ/T0IkdEvrkNHIcgFsSzDi/fV7YxzTzb3mnMvFPawuIyIrHcpxClauEfpQg==" crossorigin="anonymous" />
<script src="{% static 'js/bootstrap-datepicker.min.js' %}" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous"></script>
<script>$(document).ready(function() { $('.dateinput').datepicker(); });</script>
{% endblock %}

apps/project/templates/project/hostingservice_list.html
{% extends 'paper/layout.html'  %}
{% load static %}
{% block title %} Hosting Services | Project Management | {{ block.super }}{% endblock %}

{% block content %}
<style>
    .d-inline { display:inline-block !important}
</style>
<div class="card card-default "  id="app">
    <div class="card-header card-header-danger">
        <h4>Hosting</h4>
      <div class="box-tools pull-right">
        <a href="{% url 'project:hosting-create' %}" class="btn btn-success btn-sm">Add new Hosting</a>
      </div>
    </div>
    <hr />
    <div class="card-body">
        {% if object_list %}
        <div class="table-responsive">
            <table class="table table-bordered ">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Hosting Provider</th>
                    <th>Project</th>
                    <th>Date of Hosting</th>
                    <th>Date of Expiry</th>
                    <th>Amount</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for project in object_list %}
                <tr>
                    <td>{{ project.id }}</td>
                    <td>{{ project.name }}</td>
                    <td>{{ project.service_provider }}</td>
                    <td>{{ project.project }}</td>
                    <td>{{ project.date_of_hosting }}</td>
                    <td>{{ project.date_of_expiry }}</td>
                    <td>{{ project.amount }}</td>
                    <td>
                        <a href="{% url 'project:hosting-update' pk=project.pk %}" class="btn btn-sm btn-primary d-inline">View</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    </div>
    <div class="card-footer clearfix">
        {% include 'adminlte/lib/_pagination.html' %}
    </div>
</div>
<script>
    (function(){
        {% if messages %}
        {% for message in messages %}
            swal("{% if message.tags %}{{ message.tags }}{% endif %}", "{{ message|safe }}", "{% if message.tags %}{{ message.tags }}{% endif %}");
        {% endfor %}
        {% endif %}
    })()
    </script>
{% endblock %}


{% block extra_javascript %}
{% include 'adminlte/lib/_scripts.html' %}
<script>
</script>
{% endblock %}

apps/project/templates/project/project_form.html
{% extends 'paper/layout.html'  %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Project - {{ object.name }} | {{ block.super }}{% endblock %}

{% block stylesheets %}
{% include 'adminlte/lib/_styles.html' %}
<style>.unselectable {-webkit-touch-callout: none;-webkit-user-select: none;-khtml-user-select: none;-moz-user-select: none;-ms-user-select: none;user-select: none;} </style>
{% endblock %}
{% block content %}

<div class="card " id="app">
    <div class="card-header card-header-danger">
      {% if object.pk %}
        <h3>Update Project - {{ object.name }}</h3>
      {% else %}
        <h3>Create Project</h3>
      <div class="box-tools pull-right">
        <a href="{% url 'project:client-create' %}" class="btn btn-success btn-md">Create new Client</a>
      </div>
      {% endif %}
    </div>
        <div class="card-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-10">
                        <form method="POST" enctype="multipart/form-data">
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-primary ">Save</button>
                        </form>
                        {% if object.pk and object.client_id %}
                        <a href="{% url 'project:client-update' pk=object.client.pk %}"
                           class="btn btn-sm btn-secondary">Change Client Data</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer clearfix">
        </div>
    </div>
</div>
{% endblock %}

apps/project/templates/project/project_list.html
{% extends 'paper/layout.html'  %}
{% load static %}
{% block title %} Projects | Project Management | {{ block.super }}{% endblock %}

{% block content %}
<style>
    .d-inline { display:inline-block !important}
</style>
<div class="card card-default "  id="app">
    <div class="card-header card-header-danger">
        <h4>Projects</h4>
      <div class="pull-right">
        <a href="{% url 'project:project-create' %}" class="btn btn-success btn-sm">Create new Project</a>
      </div>
    </div>

    <div class="card-body">
        {% if object_list %}
        <div class="table-responsive">
            <table class="table table-bordered ">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Contact Number</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for project in object_list %}
                <tr>
                    <td>{{ project.id }}</td>
                    <td>{{ project.name }}</td>
                    <td><a href="tel:{{ project.concern_number }}">{{ project.concern_number }}</a>  ({{ project.concern_person }}) </td>
                    <td>
                        <a href="{% url 'project:project-update' pk=project.pk %}" class="btn btn-sm btn-primary d-inline">View</a>
                        <form action="{% url 'project:project-activation' pk=project.pk %}" method="post" class=" d-inline ">
                            <input type="hidden" hidden name="is_active" id="id_is_active" value="{% if object.is_active %}False{% else %}True{% endif %}" />
                            <button class="btn btn-{% if object.is_active %}danger{% else %}warning{% endif %} btn-sm d-inline" type="submit"> Mark as {% if object.is_active %}Closed{% else %}Active{% endif %} </button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    </div>
    <div class="card-footer clearfix">
        {% include 'adminlte/lib/_pagination.html' %}
    </div>
</div>
<script>
    (function(){
        {% if messages %}
        {% for message in messages %}
            swal("{% if message.tags %}{{ message.tags }}{% endif %}", "{{ message|safe }}", "{% if message.tags %}{{ message.tags }}{% endif %}");
        {% endfor %}
        {% endif %}
    })()
    </script>
{% endblock %}


{% block extra_javascript %}
{% include 'adminlte/lib/_scripts.html' %}
<script>
</script>
{% endblock %}

apps/project/templates/project/prospect_page.html
{% extends 'paper/layout.html'  %}
{% block title %}  {% endblock %}
{% load static crispy_forms_tags %}
{% load templatehelpers %}
{% block content %}
{% block navpage %}
<nav aria-label="breadcrumb" role="navigation" class="col-md-8 ml-1 mr-4">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active"><a href="{% url 'project:create_prospect' %}">Prospect Home</a></li>
  </ol>
</nav>
{% endblock %}
<div class="row">
    <div class="col-md-9">
        <div class="card ml-2 pl-3">
            <div class="card-body">
                <h4>Prospects List</h4>
                <form method="get">
                    <div class="row row-cols-4 pl-3">
                        {{filterdata.form|crispy}}
                        <div class="col-md-3 pl-3">
                        <button type="submit" class="btn btn-primary " style="height:40px;margin-top:20px;">Search
                        </button>
                        </div>
                    </div>
                </form>
                <hr>
                <table class="table">
                    <thead>
                    <tr class="text-center">
                        <th>#</th>
                        <th>Name</th>
                        <th>Amount</th>
                        <th>Assigned to</th>
                        <th>Status</th>
                        <th>Target Date</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    {% if filter %}
                    <tbody>
                    {% for prospect in filter %}
                    <tr class="text-center">
                        <td>{{forloop.counter}}</td>
                        <td>{{prospect.name}}<br><small>Created at:{{prospect.created_at}}</small></td>
                        <td>{{prospect.amount}}</td>
                        <td>{{prospect.assigned_to|default_if_none:"-"}}</td>
                        <td>{{prospect.status}}</td>
                        <td>{{prospect.target_date}}</td>
                        <td class="text-center d-flex justify-content-center">
                            <a class="btn btn-info btn-sm"
                               href="{% url 'project:update_prospect' prospect.pk %}">Edit</a>
                            <form action="{% url 'project:delete_prospect' prospect.pk %}" method="post">
                                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                            </form>
                        </td>
                    </tr>
                    {% empty %}
                    <tr class="text-center">
                        <td colspan="7"><h3>No Components match your search criteria</h3></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                    {% endif %}
                </table>
            </div>
            {% if filter.has_other_pages %}
            <ul class="pagination  pg-blue">
                {% if filter.has_previous %}
                <li class="page-item "><a class="page-link"
                                          href="?page={{ filter.previous_page_number }}">&laquo;</a></li>
                {% else %}
                <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                {% endif %}
                {% for i in filter.paginator.page_range %}
                {% if filter.number == i %}
                <li class="page-item active"><span class="page-link">{{ i }} <span
                        class="sr-only">(current)</span></span>
                </li>
                {% else %}
                <li class="page-item "><a class="page-link" href="{% relative_url i 'page' request.GET.urlencode %}">{{
                    i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if filter.has_next %}
                <li class="page-item "><a class="page-link"
                                          href="{% relative_url filter.next_page_number 'page' request.GET.urlencode %}">&raquo;</a>
                </li>
                {% else %}
                <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
    <div class="col-md-3">
        <div class="card mr-2 ml-2 pl-4">
            <div class="card-body">
                <a class="btn btn-info float-right" href="{% url 'project:create_billing' %}">ADD BILLING STATUS</a>
                <h4>Prospects</h4>
                <hr/>
                <form method="post">
                    {% csrf_token %}
                    <div class="col-md-12 form-group pb-5">
                        {{ form|crispy }}
                    </div>
                    <hr>
                    <div class="">
                        <button class="btn btn-success">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}